/**
* ProcessBuilderDoNothing_TEST
* Tests: ProcessBuilderDoNothing
* Date: 2018-12-14
* Programmer: Bryan Leaman
* Work item: W-000528
*
*
* Modification Log
*	Date		Developer	Work item/mod#	Description
*	----------	-----------	--------------	------------------------------------------------
*
*/
@isTest
private class ProcessBuilderDoNothing_TEST {

	 // doNothingTest
	 //---------------------------------------
	 static testMethod void doNothingTest() {
		 ProcessBuilderDoNothing.doNothing();
	 }

}