/**
* WMK (c) - 2019
*
* ReportExporterUtilityTWTest
* 
* Programmer: Alexander Miller
* Date: 3/18/2019
* Work Item:  W-000623
* Copied from: ReportExporterUtility
*
* Modified By         Alias       Work Item       Date     Reason
* -----------------------------------------------------------------
*
*/
@isTest
public class ReportExporterUtilityTWTest {

    @isTest static void testReporter(){
         
         ReportExporterUtilityTW.sendReports(); 
    }    
}